## Intro

Basic operations in tensors, conversion to and from numpy arrays.

In [2]:
import torch

In [71]:
# check whether an NVIDIA gpu is available
torch.cuda.is_available()

False

A tensor is a multi dimensional array. 

In [25]:
# Empty unidimension tensor 
e1 = torch.empty(3)
e2 = torch.empty(2,3,2)

print('e1 = ', e1)
print('e2 = ', e2)

e1 =  tensor([0.5000, 1.7197, 0.0000])
e2 =  tensor([[[-9.8885e+32,  1.3775e-42],
         [ 0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00]]])


similarly, `torch.rand()`, `torch.randint()` and `torch.zeros()` 

In [29]:
x = torch.rand((3,2))
print(x, x.dtype, x.size())

tensor([[0.4437, 0.7316],
        [0.8719, 0.5862],
        [0.5099, 0.9753]]) torch.float32 torch.Size([3, 2])


In [32]:
# to create a tensor manually by defining its entries

t1 = torch.tensor([[-1,1,0], [3,0,-2]])
print(t1, t1.shape, t1.dtype)

tensor([[-1,  1,  0],
        [ 3,  0, -2]]) torch.Size([2, 3]) torch.int64


if shape/size matches for tensors `t1` and `t2`:

- `t1+t2` or `torch.add(t1,t2)` works element-wise. 
- for inplace addition: `t1.add_(t2)` => modifies t1

General rule in pytorch: every function ending in _ performs _inplace_ operation. 

`torch.sub()`, `torch.mul()`, `torch.div()` perform namesake ops

In [35]:
t2 = torch.randint(-1, 3, (2,3))

print(t1 + t2)

tensor([[ 1,  2,  1],
        [ 3,  0, -3]])


### Slicing 

Works exactly like numpy arrays while slicing and picking rows and columns. 
- `t.item()` can be called on a scalar to get exclusively value stored in the the tensor!

In [37]:
t3 = torch.rand(3,3)
print(t3)

tensor([[0.4436, 0.5723, 0.8630],
        [0.0426, 0.2397, 0.5697],
        [0.2289, 0.5330, 0.5600]])


In [42]:
print(t3[:, 0])
print(t3[:, 0].shape)
print(t3[0][2])
print(t3[0][2].item())

tensor([0.4436, 0.0426, 0.2289])
torch.Size([3])
tensor(0.8630)
0.863018274307251


### Reshaping tensors

Core: total entries should remain conserved. 

So, size([3,4]) can be reshaped to size([2,6]) or to size([12])

`torch.reshape()` or `torch.view()` methods can be used.

In [51]:
t4 = torch.rand(3,4)
print(t4)

tensor([[0.7127, 0.4149, 0.5111, 0.1839],
        [0.5768, 0.1048, 0.7441, 0.1447],
        [0.2717, 0.7735, 0.3300, 0.4012]])


In [59]:
t4_1 = t4.reshape(-1,6) # if all other dimensions are known, plug -1 in the missing one. 
print(t4_1, t4_1.size())

tensor([[0.7127, 0.4149, 0.5111, 0.1839, 0.5768, 0.1048],
        [0.7441, 0.1447, 0.2717, 0.7735, 0.3300, 0.4012]]) torch.Size([2, 6])


### Conversion to and from numpy

<span style="color:#FF0000; font-family: 'Bebas Neue'; font-size: 01em;">NOTE:</span>
While using cpu, a and b in the below examples correspond to the same memory location and hence, modifying one will invariably modify other too!

In [68]:
a = torch.ones(5)

b = a.numpy()

print('a_tensor = ', a, 'b_ndarray = ', b)
print(type(a), type(b))

a_tensor =  tensor([1., 1., 1., 1., 1.]) b_ndarray =  [1. 1. 1. 1. 1.]
<class 'torch.Tensor'> <class 'numpy.ndarray'>


In [69]:
a.add_(1) # add 1 to each element of `a`

print(b) # b will be modified too, since both variables share pointer. 

[2. 2. 2. 2. 2.]


This shared pointer can be avoided if there is a gpu. But you have to move to and from gpu (to cpu) as necessary. A raw form of code is: 

In [72]:
# by default all tensors are created on the CPU,
# but you can also move them to the GPU (only if it's available )
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    # z = z.numpy() # not possible because numpy cannot handle GPU tenors
    # move to CPU again
    z.to("cpu")       # ``.to`` can also change dtype together!
    # z = z.numpy()