In [2]:
import torch
import torch.nn as nn

In [7]:
X = torch.randn((1000,50))
n_in = X.shape[1]

model = nn.Sequential(nn.Linear(n_in, 100, bias = True), nn.Tanh(), nn.Linear(100, 10, bias = True))

# calculate total no of params:
params = [p for layer in model for p in layer.parameters()]
print(sum(p.nelement() for p in params))

6110


In [11]:
x = torch.randn((4,4,10))
print(x.shape)

y = x.view(4,40,-1)
print(y.shape)

y = y.squeeze(dim = 2) #squeezing wrong dim keeps y.shape intact
print(y.shape)

torch.Size([4, 4, 10])
torch.Size([4, 40, 1])
torch.Size([4, 40])


In [5]:
length = lambda s : len(s)

length('Sitaram___/34!')

14

In [11]:
embd = torch.nn.Embedding(65,65)
idx = torch.randint(0,65, (2,1))

embd(idx)

tensor([[[-0.1107,  2.1620, -0.5630,  0.2965, -1.4963, -0.3796,  0.2467,
          -0.5906,  1.5520, -0.8374,  1.4317, -0.4862,  0.2719, -0.8730,
           0.5370,  0.7499, -0.0482,  0.0338,  1.4620, -0.1099,  0.9540,
           0.2469, -1.3415,  0.0955,  1.9950,  0.6704,  0.8959, -0.3795,
          -1.7980,  0.3715,  0.0510,  0.0486,  0.6389, -0.9336,  1.1644,
          -1.3099,  0.3662, -0.0218, -0.9578, -0.1643, -0.2078, -0.6938,
           0.2492,  0.2351,  0.8860, -0.1524, -1.4133,  0.1853, -0.8533,
           0.8834,  0.0347,  0.0535, -0.3400,  0.7325,  0.1745,  0.3168,
           0.8193,  0.8609,  1.4911,  1.0582,  0.0394, -0.1799,  0.7785,
           1.2308,  1.0810]],

        [[ 0.8478,  1.1869,  0.2220, -0.3144,  1.0308,  0.6402, -0.1599,
           0.0272,  2.0750,  0.9050, -0.0671, -0.6265, -0.9491,  0.9477,
          -0.1043,  1.1445, -0.6795, -0.3166, -0.5478, -1.0564,  0.4550,
           1.5283,  0.4419, -1.3361,  0.6346, -0.5142, -0.4427, -1.0389,
           0.8008, -

In [2]:
a = torch.randn((4,3,2))
a

tensor([[[ 0.8246,  0.6649],
         [ 0.6354, -0.7038],
         [ 0.1554, -0.1756]],

        [[ 0.3554,  0.6081],
         [-1.0692, -0.6263],
         [-0.4412,  0.3024]],

        [[-0.5504, -0.9069],
         [-0.8070,  1.1327],
         [-0.7694, -1.2626]],

        [[ 0.8678,  3.8454],
         [ 1.0385, -1.1645],
         [ 1.2797,  1.5052]]])

In [3]:
a.view(4,-1)

tensor([[ 0.8246,  0.6649,  0.6354, -0.7038,  0.1554, -0.1756],
        [ 0.3554,  0.6081, -1.0692, -0.6263, -0.4412,  0.3024],
        [-0.5504, -0.9069, -0.8070,  1.1327, -0.7694, -1.2626],
        [ 0.8678,  3.8454,  1.0385, -1.1645,  1.2797,  1.5052]])

In [5]:
vocab_size = 65
n_embd = 32
block_size = 8

position_embedding_table = torch.randn((block_size, n_embd))
position_embedding_table[:1]

tensor([[ 0.1568, -1.8630,  1.2676, -1.0119,  0.4661, -0.0939, -0.0666,  0.7344,
         -0.1103, -1.8737, -0.9774,  0.8607,  0.1741,  0.0422, -0.0293, -1.4745,
         -0.3180,  1.1389, -0.4212,  1.2010,  1.1812,  0.8048, -0.5440, -1.2262,
          0.2798, -0.3235, -0.1248,  0.6768,  0.0531, -1.8871, -0.4745,  0.1631]])

In [12]:
span = torch.arange(6)
# print(span)

position_embedding_table(span)

TypeError: 'Tensor' object is not callable

In [14]:
position_embedding_table[span][0]

tensor([ 0.1568, -1.8630,  1.2676, -1.0119,  0.4661, -0.0939, -0.0666,  0.7344,
        -0.1103, -1.8737, -0.9774,  0.8607,  0.1741,  0.0422, -0.0293, -1.4745,
        -0.3180,  1.1389, -0.4212,  1.2010,  1.1812,  0.8048, -0.5440, -1.2262,
         0.2798, -0.3235, -0.1248,  0.6768,  0.0531, -1.8871, -0.4745,  0.1631])

Masked_fill

In [17]:
torch.manual_seed(1337)
t1 = torch.randn((5,5))

t2 = torch.tril(torch.ones((5,5)), diagonal= 0).T # upper triangular matrix
print(t1,'\n',t2)

t1 = t1.masked_fill(t2 == 1, value= float('-inf'))
print('After masking:\n',t1)

# apply softmax
t1 = t1.softmax(dim = 1)
print('After softmax:\n', t1)


tensor([[ 0.1808, -0.0700, -0.3596, -0.9152,  0.6258],
        [ 0.0255,  0.9545,  0.0643,  0.3612, -1.0996],
        [-1.7524, -1.0971, -1.1081, -1.8002, -0.4713],
        [ 0.0084, -0.6631,  1.2055,  0.1883, -2.1600],
        [-0.1585, -0.6300, -0.2221,  0.6924, -0.5075]]) 
 tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])
After masking:
 tensor([[   -inf,    -inf,    -inf,    -inf,    -inf],
        [ 0.0255,    -inf,    -inf,    -inf,    -inf],
        [-1.7524, -1.0971,    -inf,    -inf,    -inf],
        [ 0.0084, -0.6631,  1.2055,    -inf,    -inf],
        [-0.1585, -0.6300, -0.2221,  0.6924,    -inf]])
After softmax:
 tensor([[   nan,    nan,    nan,    nan,    nan],
        [1.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3418, 0.6582, 0.0000, 0.0000, 0.0000],
        [0.2074, 0.1060, 0.6866, 0.0000, 0.0000],
        [0.2039, 0.1273, 0.1913, 0.4775, 0.0000]])


Bytes, encode, decode 

In [6]:
text = "Hi my name is Cyril Mahφpa$ 🫠"

In [8]:
encoded_text = text.encode("utf-8")
print(encoded_text)

tokens = list(encoded_text)
also_tokens = list(map(int, encoded_text))

tokens == also_tokens

b'Hi my name is Cyril Mah\xcf\x86pa$ \xf0\x9f\xab\xa0'


True

In [9]:
print(tokens[:10])

[72, 105, 32, 109, 121, 32, 110, 97, 109, 101]


In [13]:
tokens.decode("utf-8") #throws error directly

AttributeError: 'list' object has no attribute 'decode'

In [17]:
vocab[72]

b'H'

In [18]:
vocab = {idx: bytes([idx]) for idx in range(256)}

bt = b"".join(vocab[k] for k in tokens)
bt.decode("utf-8")

'Hi my name is Cyril Mahφpa$ 🫠'

### Dropout

In [38]:
torch.manual_seed(155678881)
mat = torch.randint(1,10, (4,5), dtype=torch.float)
mat

tensor([[3., 2., 1., 4., 5.],
        [2., 7., 3., 8., 7.],
        [5., 3., 3., 9., 3.],
        [2., 5., 4., 2., 8.]])

In [39]:
torch.manual_seed(155678882)
drop = nn.Dropout(p = 0.2)
print(drop(mat))

tensor([[ 3.7500,  2.5000,  1.2500,  5.0000,  0.0000],
        [ 2.5000,  8.7500,  3.7500, 10.0000,  8.7500],
        [ 6.2500,  3.7500,  3.7500,  0.0000,  3.7500],
        [ 0.0000,  6.2500,  0.0000,  2.5000, 10.0000]])


inplace = True overwrites the original tensor while inplace = False creates a new variable thereby requiring more memory.  

In [40]:
drop2 = nn.Dropout(p = 0.2, inplace=True)
print(drop2(mat))

tensor([[ 0.0000,  2.5000,  1.2500,  5.0000,  6.2500],
        [ 0.0000,  0.0000,  3.7500,  0.0000,  8.7500],
        [ 6.2500,  3.7500,  3.7500, 11.2500,  0.0000],
        [ 2.5000,  0.0000,  5.0000,  2.5000, 10.0000]])


## Transposing

In [2]:
import torch

In [15]:
k = torch.randint(0,5, (2,3,4,5))
print(k.shape)
print(k.shape[::-1]) # transpose

torch.Size([2, 3, 4, 5])
torch.Size([5, 4, 3, 2])


In [ ]:
k.view(k.shape[::-1]) # reverses dimensions - idk whats the use 

In [17]:
print(f"Original shape = {k.shape} | Transposed shape = {k.mT.shape}") # regular transpose

Original shape = torch.Size([2, 3, 4, 5]) | Transposed shape = torch.Size([2, 3, 5, 4])
