In [1]:
import torch
import torch.nn as nn

In [7]:
X = torch.randn((1000,50))
n_in = X.shape[1]

model = nn.Sequential(nn.Linear(n_in, 100, bias = True), nn.Tanh(), nn.Linear(100, 10, bias = True))

# calculate total no of params:
params = [p for layer in model for p in layer.parameters()]
print(sum(p.nelement() for p in params))

6110


In [11]:
x = torch.randn((4,4,10))
print(x.shape)

y = x.view(4,40,-1)
print(y.shape)

y = y.squeeze(dim = 2) #squeezing wrong dim keeps y.shape intact
print(y.shape)

torch.Size([4, 4, 10])
torch.Size([4, 40, 1])
torch.Size([4, 40])


In [5]:
length = lambda s : len(s)

length('Sitaram___/34!')

14

In [11]:
embd = torch.nn.Embedding(65,65)
idx = torch.randint(0,65, (2,1))

embd(idx)

tensor([[[-0.1107,  2.1620, -0.5630,  0.2965, -1.4963, -0.3796,  0.2467,
          -0.5906,  1.5520, -0.8374,  1.4317, -0.4862,  0.2719, -0.8730,
           0.5370,  0.7499, -0.0482,  0.0338,  1.4620, -0.1099,  0.9540,
           0.2469, -1.3415,  0.0955,  1.9950,  0.6704,  0.8959, -0.3795,
          -1.7980,  0.3715,  0.0510,  0.0486,  0.6389, -0.9336,  1.1644,
          -1.3099,  0.3662, -0.0218, -0.9578, -0.1643, -0.2078, -0.6938,
           0.2492,  0.2351,  0.8860, -0.1524, -1.4133,  0.1853, -0.8533,
           0.8834,  0.0347,  0.0535, -0.3400,  0.7325,  0.1745,  0.3168,
           0.8193,  0.8609,  1.4911,  1.0582,  0.0394, -0.1799,  0.7785,
           1.2308,  1.0810]],

        [[ 0.8478,  1.1869,  0.2220, -0.3144,  1.0308,  0.6402, -0.1599,
           0.0272,  2.0750,  0.9050, -0.0671, -0.6265, -0.9491,  0.9477,
          -0.1043,  1.1445, -0.6795, -0.3166, -0.5478, -1.0564,  0.4550,
           1.5283,  0.4419, -1.3361,  0.6346, -0.5142, -0.4427, -1.0389,
           0.8008, -

In [2]:
a = torch.randn((4,3,2))
a

tensor([[[ 0.8246,  0.6649],
         [ 0.6354, -0.7038],
         [ 0.1554, -0.1756]],

        [[ 0.3554,  0.6081],
         [-1.0692, -0.6263],
         [-0.4412,  0.3024]],

        [[-0.5504, -0.9069],
         [-0.8070,  1.1327],
         [-0.7694, -1.2626]],

        [[ 0.8678,  3.8454],
         [ 1.0385, -1.1645],
         [ 1.2797,  1.5052]]])

In [3]:
a.view(4,-1)

tensor([[ 0.8246,  0.6649,  0.6354, -0.7038,  0.1554, -0.1756],
        [ 0.3554,  0.6081, -1.0692, -0.6263, -0.4412,  0.3024],
        [-0.5504, -0.9069, -0.8070,  1.1327, -0.7694, -1.2626],
        [ 0.8678,  3.8454,  1.0385, -1.1645,  1.2797,  1.5052]])

In [5]:
vocab_size = 65
n_embd = 32
block_size = 8

position_embedding_table = torch.randn((block_size, n_embd))
position_embedding_table[:1]

tensor([[ 0.1568, -1.8630,  1.2676, -1.0119,  0.4661, -0.0939, -0.0666,  0.7344,
         -0.1103, -1.8737, -0.9774,  0.8607,  0.1741,  0.0422, -0.0293, -1.4745,
         -0.3180,  1.1389, -0.4212,  1.2010,  1.1812,  0.8048, -0.5440, -1.2262,
          0.2798, -0.3235, -0.1248,  0.6768,  0.0531, -1.8871, -0.4745,  0.1631]])

In [12]:
span = torch.arange(6)
# print(span)

position_embedding_table(span)

TypeError: 'Tensor' object is not callable

In [14]:
position_embedding_table[span][0]

tensor([ 0.1568, -1.8630,  1.2676, -1.0119,  0.4661, -0.0939, -0.0666,  0.7344,
        -0.1103, -1.8737, -0.9774,  0.8607,  0.1741,  0.0422, -0.0293, -1.4745,
        -0.3180,  1.1389, -0.4212,  1.2010,  1.1812,  0.8048, -0.5440, -1.2262,
         0.2798, -0.3235, -0.1248,  0.6768,  0.0531, -1.8871, -0.4745,  0.1631])