In [3]:
import math
import numpy
import torch.nn as nn
import torch
import torch.nn.functional as F

In [19]:
a = [1,2,3,4]
b = ['apple', 'ball', 'cat', 'dungeon', 'eucalyptus']
c = ['RCB', 'CSK', 'MI']

# zip object is natively stored as a collection of tuples and
# constrained by list with least elements
zipped_obj = list(zip(a,b,c))   
print(f'Zip(a,b,c): {zipped_obj}')

# indexing/slicing is possible
for i in zipped_obj:
    print(i[1:])

Zip(a,b,c): [(1, 'apple', 'RCB'), (2, 'ball', 'CSK'), (3, 'cat', 'MI')]
('apple', 'RCB')
('ball', 'CSK')
('cat', 'MI')


In [3]:
names = ['Olivia', 'Clementine', 'Claire', 'Martha']

for name in names[:1]:
    for i,j in zip(name, name[1:]):
            print(i,j)

O l
l i
i v
v i
i a


In [ ]:
# .join method can be called on any string - which then acts as a connector

print(''.join(set(names)))

print('; '.join(set(names)))

ClaireClementineOliviaMartha
Claire; Clementine; Olivia; Martha


In [ ]:
# set: identifies the unique chars in the combined string

s1 = set(''.join(set(names)))
print(sorted(s1))

['C', 'M', 'O', 'a', 'e', 'h', 'i', 'l', 'm', 'n', 'r', 't', 'v']


In [28]:
int_to_str = [(i,s) for i,s in enumerate(s1)]
print(int_to_str[:3] )# as list

# as dict is more useful
int_to_str_asdict = {i:s for i,s in enumerate(s1)}
print(int_to_str_asdict)


[(0, 'M'), (1, 'e'), (2, 'n')]
{0: 'M', 1: 'e', 2: 'n', 3: 'l', 4: 'O', 5: 'r', 6: 'C', 7: 'a', 8: 't', 9: 'h', 10: 'm', 11: 'v', 12: 'i'}


In [ ]:
# enumerate(any_list) create a second iterable along with the entries in any_list itself. 
for i,j in enumerate(names):
    print(i,j)

0 Olivia
1 Clementine
2 Claire
3 Martha


In [20]:
dict = {'Severance':'liminal', 'The Boys': 'dystopian' , 'Narcos':'drugs', 'Hangover':'nostalgia' }

# by default iterates over keys 
for i,j in enumerate(dict):
    print(i,j)

print('-----------------')

# to iterate over values, state explicitly 
for i,j in enumerate(dict.values()):
    print(i,j)

0 Severance
1 The Boys
2 Narcos
3 Hangover
-----------------
0 liminal
1 dystopian
2 drugs
3 nostalgia


## Getting back in shape after a long gap

In [10]:
l1 = ['car', 'bus', 'train']
l2 = ['Mumbai', 'chennai', 'delhi']
l3 = [101, -1, 909]

for c1,c2 in zip(l1,l1[1:]):
    print(c1,c2)


car bus
bus train


In [11]:
for c1,c2 in zip(l1[0],l1[0][1:]):
    print(c1,c2)

c a
a r


In [ ]:
records = {'Sam':5, 'Elon':7, 'Jeff':-1, 'William':4}

print(sorted(records.items(), key = lambda kv: kv[1]))

print(sorted(records.items(), key = lambda kv: -kv[1]))

[('Jeff', -1), ('William', 4), ('Sam', 5), ('Elon', 7)]
[('Elon', 7), ('Sam', 5), ('William', 4), ('Jeff', -1)]


In [34]:
names = list(records.keys())

chars = set(''.join(names))
chars = sorted(chars)
chars

['E', 'J', 'S', 'W', 'a', 'e', 'f', 'i', 'l', 'm', 'n', 'o']

In [33]:
stoi = {s:i for i,s in enumerate(chars)}
stoi

{'E': 0,
 'J': 1,
 'S': 2,
 'W': 3,
 'a': 4,
 'e': 5,
 'f': 6,
 'i': 7,
 'l': 8,
 'm': 9,
 'n': 10,
 'o': 11}

In [17]:
# normalization along rows

import torch 

N = torch.tensor([[1,2,5], [2,2.5,6]])
s = N.sum(dim = 1)
print(N,s)

for i in range(N.shape[0]):
    N[i] = N[i]/s[i]

print('Post normalization = ', N)

tensor([[1.0000, 2.0000, 5.0000],
        [2.0000, 2.5000, 6.0000]]) tensor([ 8.0000, 10.5000])
Post normalization =  tensor([[0.1250, 0.2500, 0.6250],
        [0.1905, 0.2381, 0.5714]])


[Check rules of broadcasting](https://docs.pytorch.org/docs/stable/notes/broadcasting.html) and the use of `keepdim` argument in [calculation of row-wise or col-wise sums](https://docs.pytorch.org/docs/stable/generated/torch.sum.html). 

In [24]:
N2 = torch.rand(4,3)
sum_with_keepdim = N2.sum(1, keepdim=True)
sum_wo_keepdim = N2.sum(1)

In [25]:
sum_with_keepdim.shape, sum_wo_keepdim.shape

(torch.Size([4, 1]), torch.Size([4]))

In [26]:
N2_1 = N2 / sum_with_keepdim
N2_2 = N2/ sum_wo_keepdim

RuntimeError: The size of tensor a (3) must match the size of tensor b (4) at non-singleton dimension 1

This error indicates that when `keepdim = False`, the sum tensor is a 1D array and by broadcasting principles apply along the column, _not along row_, as is expected -- which will happen only if `keepdim = True`!

In [28]:
N2_1 # normalize along row 

tensor([[0.1252, 0.0233, 0.8515],
        [0.4742, 0.0854, 0.4405],
        [0.1159, 0.3869, 0.4971],
        [0.1630, 0.6686, 0.1684]])

using `torch.nn.functional.one_hot()`: 

[documentation](https://docs.pytorch.org/docs/stable/generated/torch.nn.functional.one_hot.html)

In [31]:
import torch.nn as nn
torch.arange(0,6)

tensor([0, 1, 2, 3, 4, 5])

In [32]:
nn.functional.one_hot(torch.arange(0,6) % 4, num_classes=5)

tensor([[1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0]])

another interesting way to generate one hot encoding:

In [38]:
torch.arange(1,10,2) % 4 # mod applies for all elements in the tensor

tensor([1, 3, 1, 3, 1])

In [39]:
nn.functional.one_hot(torch.arange(1,10,2) % 4, num_classes=6)

tensor([[0, 1, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0],
        [0, 1, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0],
        [0, 1, 0, 0, 0, 0]])

## Indexing in higher dimension tensors

In [6]:
# consider C
C = torch.randn((27,2)) # 27 character each with a 2D embedding. 
C[:3]

tensor([[ 2.1214, -1.0391],
        [-0.5244,  0.0549],
        [ 0.0782, -0.2522]])

In [ ]:
C[[0,2,2,4,6]] # extracts 0th, 2nd*2, 4th, 6th rows of C into a new tensor

tensor([ 2.1214, -1.0391])

In [12]:
X = torch.randint(low=0, high=27, size= (16,3)) # context matrix

In [13]:
X[:3]

tensor([[22, 26,  1],
        [ 0, 14, 15],
        [ 2, 24,  0]])

## Concatenation in torch

In [9]:
x1 = torch.tensor([[1,2], [3,4]])
print(x1.shape)
x2 = torch.cat((x1,x1) ,dim = 1)
print(x2.shape, x2)

torch.Size([2, 2])
torch.Size([2, 4]) tensor([[1, 2, 1, 2],
        [3, 4, 3, 4]])


[torch.unbind()](https://docs.pytorch.org/docs/stable/generated/torch.unbind.html#torch-unbind): __returns a tuple__  of all slices along a given dimension, already without it.

In [16]:
x3 = torch.unbind(x1, dim = 1)
print(x1, x3)

tensor([[1, 2],
        [3, 4]]) (tensor([1, 3]), tensor([2, 4]))


In [25]:
x4 = torch.randn((16,5,4))
print(x4.shape)

x5 = torch.unbind(x4, dim = 0) # dim 0 disappears
print(len(x5), x5[0].shape) # 5*4 ke 16 entries

x6 = torch.unbind(x4, dim = 1)
print(len(x6), x6[0].shape, x6[0].type())


torch.Size([16, 5, 4])
16 torch.Size([5, 4])
5 torch.Size([16, 4]) torch.FloatTensor


### On storage efficiency:

In [32]:
a = torch.arange(18)
a

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [33]:
a.storage()

 0
 1
 2
 3
 4
 5
 6
 7
 8
 9
 10
 11
 12
 13
 14
 15
 16
 17
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 18]

In [35]:
print('cast 1 = ', a.view(2,9), 'cast 2 = ',a.view(3,6), 'cast 3 = ', a.view(2,3,3))

cast 1 =  tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17]]) cast 2 =  tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17]]) cast 3 =  tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]])


Some indexing play

In [4]:
labels = torch.randint(0,26, (16,))
labels

tensor([ 8,  1, 20, 13, 24,  9,  9,  9,  3, 15, 10, 21,  7, 14, 13, 24])

In [5]:
prob = torch.randn((16,27))
prob = torch.softmax(prob, dim = 1)

In [6]:
len(labels)

16

In [16]:
for i in range(len(labels)):
    print(i,' |', labels[i].item(),'|' ,f"{prob[i, labels[i]].item():.4f}")

0  | 8 | 0.0305
1  | 1 | 0.0322
2  | 20 | 0.0125
3  | 13 | 0.0100
4  | 24 | 0.0146
5  | 9 | 0.0915
6  | 9 | 0.0375
7  | 9 | 0.0378
8  | 3 | 0.0571
9  | 15 | 0.1752
10  | 10 | 0.0153
11  | 21 | 0.0262
12  | 7 | 0.0448
13  | 14 | 0.0119
14  | 13 | 0.0590
15  | 24 | 0.0103


In [39]:
t1 = torch.randint(-2,4, (3,4), dtype=torch.float)
t2 = torch.rand((3,4))

target = torch.tensor([1,0,2])

In [40]:
L1 = F.cross_entropy(t1, target)
L2 = F.cross_entropy(t2, target)
print(L1,L2)

tensor(1.1098) tensor(1.3455)


In [41]:
t2

tensor([[0.6942, 0.5390, 0.7971, 0.3440],
        [0.4968, 0.6837, 0.8640, 0.8919],
        [0.0962, 0.2678, 0.9996, 0.6256]])